### ISSUE TITLE
Not published to rubygems

### ISSUE THREAD

**Issue by jlambert121** [voxpupuli/puppet-lint-classes_and_types_beginning_with_digits-check#1]
It looks like this lint check is not published to rubygems.

**Comment by igalic** [comment]
@raphink ping

**Comment by raphink** [comment]
This plugin was created by @glarizza. I wouldn't mind publishing it with my account, but I think @glarizza should give his go first (also for his other plugins).

**Comment by glarizza** [comment]
Apologies, I wasn't getting notifications on this repo.  Eeks.   Also, this is awkward --> https://rubygems.org/gems/puppet-lint-classes_and_types_beginning_with_digits--check

See that extra dash at the end?  It means I'm a moron and can't type.  Fixed the spec and pushed to --> https://rubygems.org/gems/puppet-lint-classes_and_types_beginning_with_digits-check

**Comment by raphink** [comment]
@glarizza Could you add your rubygems API key (encrypted) to .travis.yml or add me as owner on rubygems, so we can setup CD for this plugin please?

**Comment by glarizza** [comment]
Which email do you prefer I use for adding an owner, Raphaël?

On Wed, Apr 8, 2015 at 7:58 AM, Raphaël Pinson notifications@github.com
wrote:

> @glarizza https://github.com/glarizza Could you add your rubygems API
> key (encrypted) to .travis.yml or add me as owner on rubygems, so we can
> setup CD for this plugin please?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/puppet-community/puppet-lint-classes_and_types_beginning_with_digits-check/issues/1#issuecomment-90941905
> .

## 

Gary Larizza
Professional Services Engineer
Puppet Labs

http://garylarizza.com

**Comment by raphink** [comment]
rubygems-to8oesegoo [at] raphink [dot] net

**Comment by glarizza** [comment]
You should be an owner!  I'll set you up on the other repo too

On Wed, Apr 8, 2015 at 8:34 AM, Raphaël Pinson notifications@github.com
wrote:

> rubygems-to8oesegoo [at] raphink [dot] net
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/puppet-community/puppet-lint-classes_and_types_beginning_with_digits-check/issues/1#issuecomment-90952615
> .

## 

Gary Larizza
Professional Services Engineer
Puppet Labs

http://garylarizza.com

**Comment by raphink** [comment]
Thanks, I'll set up publishing then.

**Comment by raphink** [comment]
There, I set it up. Contributors can now publish this gem by tagging the repo.

**Comment by nibalizer** [comment]
Awesome.
